### PR TITLE
Add Company dataclass, resolve issue #12

### PR DESCRIPTION
**Pull request by mulliganw**

### CODE REVIEW

**Comment by mulliganw** [comment]
tried to add owner: int to the dataclass, not sure it went through or not

**Comment by JackChuck1** [comment]
Maybe instead of rent we could have a multiplier that updates based on how many companies the player owns, since that's how companies calculate rent

**Comment by mulliganw** [comment]
> Maybe instead of rent we could have a multiplier that updates based on how many companies the player owns, since that's how companies calculate rent

i thought we established that it didnt have a pattern

**Comment by JackChuck1** [comment]
> > Maybe instead of rent we could have a multiplier that updates based on how many companies the player owns, since that's how companies calculate rent
> 
> i thought we established that it didnt have a pattern

Its a company, the amount of rent you get is either 2x or 10x ur dice roll I believe

**Comment by JackChuck1** [comment]
Not fan, we should make a dif company data class with a multiplier.

**Comment by mulliganw** [comment]
i think i did an oops, the thing just closed itself and removed a bunch of commits because i synced my fork with main cuz i thought it would be easier but it wasnt :(

**Pull request closed without merging**
